# Generated by Django 4.2.7 on 2025-06-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person making the request', max_length=200)),
                ('email', models.EmailField(help_text='Email address for contact', max_length=254)),
                ('phone', models.CharField(help_text='Phone number for contact', max_length=20)),
                ('services_needed', models.JSONField(default=list, help_text='List of services requested (selected from SERVICE_CHOICES)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when request was created')),
            ],
            options={
                'verbose_name': 'Contact Request',
                'verbose_name_plural': 'Contact Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
